### ISSUE TITLE
Fix MER cart's quantity field inputs so they don't allow adding more tickets allowed per event per order

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/ee4-mer#6] opened 2018-10-29 16:44 UTC
From Codebase: https://events.codebasehq.com/projects/event-espresso/tickets/8473 

This is similar to the issue reported in #8451, the difference being instead of clicking on the + button, you input a bigger number than allowed in the quantity input field.

1. Set the Maximum number of tickets allowed per order for this event: setting to something like 5, save
2. Set up two tickets for the event 
3. Go to view the event and select 2 tickets of each (total 4 tickets)
4. Click add to cart
5. Click view event cart
6. Type 3 in the inputs field where it says 2 to add more tickets to the cart (more than allowed)
7. Click Update Event Cart
8. Proceed to registration

The unexpected result is it lets you add more tickets to the cart than allowed and checkout.
reported here:
http://eventespresso.com/topic/bug-maximum-number-of-tickets-not-working-on-event-cart/

Brent Christensen commented on Wednesday 8th July 2015 at 12:17pm
#branch MER addon master

###Testing

 * follow the steps outlined above by Josh 
 * [ ] confirm that event max tickets is not exceeded

Josh Feck commented on Wednesday 8th July 2015 at 12:29pm
This fixes the issue originally reported here. Is it expected to throw the error if you try to update quantities for both tickets and update the cart? For example, if I start with 2 of ticket A and 3 of ticket B, but I try to type in 3 for ticket A and 2 for ticket B, it gives me the error when I update the cart. Here's a link to a little video that shows the scenario:

http://screencast.com/t/lVjDXzOT

Lorenzo Caum commented on Monday 18th January 2016 at 6:15am
A report through Help Scout sales:

https://secure.helpscout.net/conversation/161835334/178580/?folderId=100617

Lorenzo Caum commented on Monday 28th March 2016 at 11:51am
One more report:

https://eventespresso.com/topic/customer-can-change-quantity-for-graduated-pricing-other-than-maxmin/

Josh Feck commented on Wednesday 29th June 2016 at 4:21pm
related to #9450 - Fix MER cart so it doesn't allow adding more tickets to the cart allowed per event per order from the event list

Josh Feck commented on Wednesday 7th September 2016 at 7:27am
reported again here:

https://eventespresso.com/topic/min-max-ticket-qty/

Josh Feck commented on Monday 17th April 2017 at 9:30am
Reported again in the forums here:

https://eventespresso.com/topic/minimum-and-maximum-ticket-quantity-bug-in-event-cart/

Lorenzo Caum commented on Monday 24th July 2017 at 8:02am
https://secure.helpscout.net/conversation/387224000/386913/

Josh Feck commented on Friday 8th June at 11:28am
update about this issue requested here:

https://eventespresso.com/topic/minimum-ticket-bug-update-request/

**Comment by sethshoultes** [comment] 2018-10-29 16:45
Related issue https://github.com/eventespresso/ee4-mer/issues/5

**Comment by tn3rb** [comment] 2019-01-18 17:22
totally a duplicate of #5

**Closed by tn3rb** 2019-01-18 17:22 UTC
Labels: category:accessibility, status:potential-duplicate

**Comment by joshfeck** [comment] 2020-02-21 16:28
Not a duplicate of #5 because in this case the issue happened on the cart page, not on the event list page. In any case, it's no longer an issue that can be reproduced.

![Screen Shot 2020-02-21 at 11 26 37 AM](https://user-images.githubusercontent.com/891156/75052203-34c2c600-549d-11ea-906b-26f25340a926.png)
